version: '3.3'
services:
  db:
    container_name: db
    hostname: db
    image: mariadb:5.5.61
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=rootpass
    - MYSQL_DATABASE=my_db
    - MYSQL_USER=my_user
    - MYSQL_PASSWORD=mypassword
    ports:
    - 3306:3306
    volumes:
    - ./data/mariadb:/var/lib/mysql

  adminer:
    # https://hub.docker.com/_/adminer/
    # https://github.com/vrana/adminer/tree/master/designs
    container_name: adminer
    hostname: adminer
    image: adminer:4.6.3-standalone
    restart: always
    environment:
    - ADMINER_DESIGN=nette
    ports:
    - 8080:8080
