version: '3.3'
services:
  db:
    container_name: db
    hostname: db
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=nest
    - POSTGRES_PASSWORD=nest
    - POSTGRES_DB=nest
    ports:
    - 3306:3306
    volumes:
    - database-data:/var/lib/postgresql/data/

  adminer:
    # https://hub.docker.com/_/adminer/
    # https://github.com/vrana/adminer/tree/master/designs
    container_name: adminer
    hostname: adminer
    image: adminer:4.6.3-standalone
    restart: always
    environment:
    - ADMINER_DESIGN=nette
    ports:
    - 8080:8080
